#! /bin/sh

cd /lib/modules/$(uname -r)/extra

case "$1" in
  start)
    echo "Loading aesd-char driver"
    aesdchar_load
    ;;
  stop)
    echo "Unloading aesd-char driver"
    aesdchar_unload
    ;;
  *)
    echo "Usage: $0 {start | stop}"
  exit 1
  esac

  exit 0

  # Reference:
  # Simmonds, Chris. Mastering Embedded Linux Programming - Second Edition,
  # Packt Publishing, Limited, 2017. ProQuest Ebook Central,
  # http://ebookcentral.proquest.com/lib/ucb/detail.action?docID=4898669.# 
